### ISSUE TITLE
I'm experiencing an error building nanopineo2

### ISSUE THREAD

**Issue by Wanderingkang** [volumio/volumio3-os#110]
root@DESKTOP-N4H162K:~/volumio3# ./build.sh -b armv8 -d nanopineo2 -v 2.1.
[ .... ] Running Volumio Image Builder -
[ .. ] Checking whether we are running as root
[ .. ] Creating log directory
[ .. ] Setting default Volumio variant
[ .... ] Creating armv8 rootfs
[ .. ] armv8 rootfs exists, cleaning it
[ .... ] Setting up Multistrap environment
[ .. ] Preparing rootfs apt-config
[ .. ] Adding SecureApt keys to rootfs
Executing: /tmp/apt-key-gpghome.7jPoEKdrAA/gpg.1.sh --fetch-keys https://archive.raspbian.org/raspbian.public.key
gpg: requesting key from 'https://archive.raspbian.org/raspbian.public.key'
gpg: connecting dirmngr at '/run/user/0/gnupg/d.end3wh1qf9mxm8gcx9ih19dm/S.dirmngr' failed: IPC connect call failed
gpg: WARNING: unable to fetch URI https://archive.raspbian.org/raspbian.public.key: No dirmngr

**Comment by Wanderingkang** [comment]
When I uninstall gpg install gnupg1 report such error

root@DESKTOP-N4H162K:~/volumio3# ./build.sh -b armv8 -d nanopineo2 -v 2.1.
[ .... ] Running Volumio Image Builder -
[ .. ] Checking whether we are running as root
[ .. ] Creating log directory
[ .. ] Setting default Volumio variant
[ .... ] Creating armv8 rootfs
[ .. ] armv8 rootfs exists, cleaning it
[ .... ] Setting up Multistrap environment
[ .. ] Preparing rootfs apt-config
[ .. ] Adding SecureApt keys to rootfs
Executing: /tmp/apt-key-gpghome.vn2gshrIo2/gpg.1.sh --fetch-keys https://archive.raspbian.org/raspbian.public.key
gpg: key 90FDDD2E: public key "Mike Thompson (Raspberry Pi Debian armhf ARMv6+VFP) <mpthompson@gmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
Executing: /tmp/apt-key-gpghome.43BiwRUSqa/gpg.1.sh --fetch-keys https://repo.volumio.org/Volumio2/archive-key-10.asc
gpg: key 3CBBABEE: public key "Debian Archive Automatic Signing Key (10/buster) <ftpmaster@debian.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
Executing: /tmp/apt-key-gpghome.GZeJakLwYK/gpg.1.sh --fetch-keys http://archive.raspberrypi.org/debian/raspberrypi.gpg.key
gpg: key 7FA3303E: public key "Raspberry Pi Archive Signing Key" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
Executing: /tmp/apt-key-gpghome.vKKImTx0Nu/gpg.1.sh --fetch-keys https://deb.nodesource.com/gpgkey/nodesource.gpg.key
gpg: key 68576280: public key "NodeSource <gpg@nodesource.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
Executing: /tmp/apt-key-gpghome.JKR1A71Dy5/gpg.1.sh --fetch-keys https://www.lesbonscomptes.com/pages/jf-at-dockes.org.pub
gpgkeys: no key data found for https://www.lesbonscomptes.com/pages/jf-at-dockes.org.pub
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: key not found
gpg: keyserver communications error: bad public key
gpg: WARNING: unable to fetch URI https://www.lesbonscomptes.com/pages/jf-at-dockes.org.pub: bad public key

**Comment by Darmur** [comment]
please build with armv7 option, armv8 does not work in most of the cases

**Comment by Darmur** [comment]
did you try with armv7 option?

**Comment by Darmur** [comment]
are you running the build script from a Debian Buster system?
