### ISSUE TITLE
Userconfig.txt overfilled

### ISSUE THREAD

**Issue by volumio** [volumio/volumio3-os#14]
The userconfigt.txt gets overfilled after each update

# Add your custom config.txt options to this file, which will be preserved during updates
# Add your custom config.txt options to this file, which will be preserved during updates# Add your custom config.txt options to this file, which will be preserved during updates
# Add your custom config.txt options to this file, which will be preserved during updates
# Add your custom config.txt options to this file, which will be preserved during updates
# Add your custom config.txt options to this file, which will be preserved during updates
# Add your custom config.txt options to this file, which will be preserved during updates
# Add your custom config.txt options to this file, which will be preserved during updates
# Add your custom config.txt options to this file, which will be preserved during updates
# Add your custom config.txt options to this file, which will be preserved during updates
# Add your custom config.txt options to this file, which will be preserved during updates

**Comment by ashthespy** [comment]
https://github.com/volumio/Build/pull/472#issue-802371273

**Comment by volumio** [comment]
Actually, you are right. But that should work out of the box, if firststart.sh is properly disabled.
Maybe we shall add

I wonder where it gets adedd then... Firstart service is disabled by firststart.sh ...

**Comment by ashthespy** [comment]
> I wonder where it gets adedd then... Firstart service is disabled by firststart.sh ...

Could it be the previous method seems to have just mask the running of first start on every update?

**Comment by ashthespy** [comment]
Addressed in 77d3feca807bf0e1337267bc056fd30bb9766f39
