### ISSUE TITLE
GPIO Buttons plugin bug

### ISSUE THREAD

**Issue by andreu4448** [volumio/volumio3-os#252]
I installed the Volumio OS on a Raspberry Pi 4 with the Innomaker DAC hat. I installed a power button and the corresponding GPIO Buttons plugin. Everything worked properly after setting it up and installing plugins and music sources.

The following morning, there was no sound, but the interface seemed to work fine, and the playback, although very slow and non-responsive, seemed to work (time was running, and when changing songs, it was picking it up). After changing things around, I at last managed to get an error that could help me debug:
![image](https://github.com/user-attachments/assets/117b007c-6e5b-4bf2-af62-c9e6dc257532)

However, I didn´t find any documentation related to this.

After many back-and-forth reinstalls and testing, I narrowed it down to the power button. 
- With a fresh install, all works and audio are played through the hat.
- When the power button is installed on GPIO3 but without the plugin installed, all works
- When the plugin is installed, there is no audio and error above.

**Comment by Darmur** [comment]
GPIO3 is required by the DAC, if you use it with a push-button the DAC won't work anymore

you must use another GPIO for the power button

**Comment by andreu4448** [comment]
Thanks mate, I went nuts the other day trying to understand what was up
