### ISSUE TITLE
`libjson-glib` is missing for spotify plugin

### ISSUE THREAD

**Issue by mstruebing** [volumio/volumio3-os#28]
I'm not sure if volumio3-os is responsible for this or the plugin itself.
But after installing the spotify plugin on a fresh install I got the message in the UI that I can not log in.
I looked into `journalctl -f` to see what's happening and saw this error message:

```
Jan 13 12:49:13 music systemd[1]: Started Spotify Daemon.
Jan 13 12:49:13 music volumio[1308]: /usr/bin/spopd: error while loading shared libraries: libjson-glib-1.0.so.0: cannot open shared object file: No such file or directory
```

After installing the package (`libjson-glib-1.0-0`) it worked.

**Comment by mstruebing** [comment]
It's a Raspberry PI:

```
volumio@music:~$ uname -a
Linux music 5.4.83-v7+ #1379 SMP Mon Dec 14 13:08:57 GMT 2020 armv7l GNU/Linux
```

**Comment by ashthespy** [comment]
Are you sure the plugin install was successful? This should be a plugin installation issue, as the `libjson-glib-1.0-0` is already installed (or attempted) during [plugin installation](https://github.com/volumio/volumio-plugins-sources/blob/fa8b6ecdb02ecaeac14ed25169c1ba3fe8e1f160/spotify/install.sh#L5). 
It's a different matter that a bunch of build dependencies are also probably being installed..

**Comment by mstruebing** [comment]
On the first go it was hanging and my PI restarted, on the second attempt it installed successful. 
I did not had a deeper look into the docs as it seemed good to me.
So it might be a non-issue and specific to the first failure.

Thanks.
