### ISSUE TITLE
BeagleBone Black device

### ISSUE THREAD

**Issue by gunbatt** [volumio/volumio3-os#34]
Is it possible to add the BeagleBone Black supported device list?

**Comment by volumio** [comment]
Unfortunately no, this device is too old and from what we know, no-one is using it

**Comment by gunbatt** [comment]
I use this device and have been for a very long time. The sound is just great. It would be nice to upgrade to the new version Volumio 3.
![bbb_b](https://user-images.githubusercontent.com/56196929/153416040-0fa16517-6828-43f4-bf67-08fb686ad515.jpg)
![bbb_f](https://user-images.githubusercontent.com/56196929/153416044-b88c7838-412b-4b3a-93fd-9d92e734a644.jpg)
![bbb_t](https://user-images.githubusercontent.com/56196929/153416045-e7eea491-3c98-4ed6-b118-de9eaf0b0862.jpg)

**Comment by volumio** [comment]
Very nice indeed!
If it's possible, I suggest to replace BBB with PI4 (or Tinkerboard S).
You'll get a nice speed bonus + OOTB Volumio3

**Comment by ashthespy** [comment]
> Is it possible to add the BeagleBone Black supported device list?

Everything is possible - the question is if it's worth it ;-) 
To add it to the new build system should be straight forward - Gé and me only added devices we own and can test.. 
It should be rather trivial - you don't need to do any [porting](https://volumio.github.io/docs/Porting_Guide/Introduction.html) per say, but just transfer things to the new device template. 
You would just need to pull in [`volumio/platform-bbb`](https://github.com/volumio/platform-bbb) and copy some parameters over from [`bbbconfig.sh`](https://github.com/volumio/Build/blob/master/scripts/bbbconfig.sh) and [`bbbimage.sh`](https://github.com/volumio/Build/blob/master/scripts/bbbimage.sh)

So if you have the resources and inclination, nothing stopping you - but you could have guessed by now that this isn't something particularly interesting device for the team :-)
