### ISSUE TITLE
feature request for console =>"PS" -> /etc/profile

### ISSUE THREAD

**Issue by camelcamro** [volumio/volumio3-os#43]
maybe we can add to profile, something like that ?
.) to see user name ?
.) to see in which directory the user is ?
`.) and to have that in colored ?

like that:
export PS1='\[\033[0;32m\]\u@\H:\[\033[36m\]$PWD\[\033[0m\] \$ '
[ "$TERM" = "xterm" ] && export PS1='\[\e]0;\u@\h: \w\a\]'$PS1

**Comment by ashthespy** [comment]
You can do this trivially for your own device by adding the line to `~/.bashrc` as each person usually will want a different style ;)

**Comment by volumio** [comment]
Feel free to send a PR with the aliases you would like to be included.
