### ISSUE TITLE
hostname wrong with umlaut

### ISSUE THREAD

**Issue by dflvunoooooo** [volumio/volumio3-os#52]
If I choose in the onboarding process a hostname with an ä ö or ü, the hostname is not set correctly. The umlaut is simply omitted, but the gui is displaying the expected hostname with the umlaut.

![Screenshot_20220912_154916](https://user-images.githubusercontent.com/32816598/189675201-d93a526b-dc78-4fe0-b2ed-b07314d6e629.png)

On the other hand, `cat /etc/hostname` results `volumio-kche`.

**Comment by ashthespy** [comment]
> On the other hand, cat /etc/hostname results volumio-kche.

See https://github.com/volumio/Volumio2/issues/253 and https://github.com/volumio/Volumio2/pull/1530#issuecomment-383507205 for some history. 

But, this issue belongs in [/volumio/volumio3-backend](https://github.com/volumio/volumio3-backend) where the code to write the player name to the host file resides. 
Technically, if you use IDNA's ASCII representation ( `Volumio-Küche` ==> `xn--volumio-kche-llb`) in `/etc/hostname` should work as expected.
