### ISSUE TITLE
Debian buster EOL

### ISSUE THREAD

**Issue by ashthespy** [volumio/volumio3-os#53]
FYI: https://www.debian.org/News/2022/20220910
Buster is officially EOL, with the last security update (10.13) released on 10.09.2022. 

Is the plan to stay on Buster LTS or move to current stable Debian in the near future?

**Comment by volumio** [comment]
If you know who is willing to jump on it, then of course yes ;)

**Comment by ashthespy** [comment]
I did do some stuff over in https://github.com/volumio/Build/issues/516 but it must be something on your internal roadmap for anyone to jump on it ;)

**Comment by ashthespy** [comment]
FWIW, I just found this from 2021 https://community.volumio.org/t/volumio-debian-bullseye-alpha-raspi-images/48929

**Comment by volumio** [comment]
I just think that @mervinderuiter just did not see it when it started working on the feature. sorry to make you waste time

**Comment by ashthespy** [comment]
>I just think that @mervinderuiter just did not see it when it started working on the feature. sorry to make you waste time 

I'm confused, is there a Bullseye release in development already?

**Comment by volumio** [comment]
Sorry, wrong comment: I was referring to the timezone setting, not buster

**Comment by ashthespy** [comment]
Closing in favor of #172
