### ISSUE TITLE
Repo size

### ISSUE THREAD

**Issue by ashthespy** [volumio/volumio3-os#54]
It would seem that in the shift from [volumio/Build](https://github.com/volumio/Build), one of motivations for having a new repo wasn't implemented - namely https://github.com/volumio/Build/issues/413?

We still have quite leftovers from `./platforms` in the repo, making clones ~47 MiB..

```
checkRepoBloat.sh 
.
.
.
418c87428972  690KiB platforms/cuboxi/lib/modules/3.14.14-cubox/kernel/fs/xfs/xfs.ko
5e5483ca6175  829KiB platforms/cuboxi/lib/modules/3.14.14-cubox/kernel/fs/ocfs2/ocfs2.ko
e6b434f0b652  974KiB platforms/cuboxi/lib/modules/3.14.14-cubox/kernel/fs/btrfs/btrfs.ko
d7856a9257e0  1.0MiB platforms/cuboxi/uboot/u-boot.img
761f410bc473  4.1MiB platforms/udoo/boot/uImage
d035e5869856  5.7MiB platforms/cuboxi/boot/zImage
Total: 118MiB
```

**Comment by volumio** [comment]
Do you have a proposal on how to get rid of this file history?

**Comment by ashthespy** [comment]
Multiple proposals are in https://github.com/volumio/Build/issues/413 
https://github.com/volumio/Build/issues/413#issuecomment-646319461
https://github.com/volumio/Build/issues/413#issuecomment-752301893

But since this wasn't done during the switch to this repo, you will have to break all history (`push -f`).

Also the naming scheme of this repo is confusing, (OS version previously  wasn't linked to the backend/nodjs-app version) 
but going forward will Bullseye be called Volumio 4?

Perhaps that is a good thing, and you could think yet another repo, archiving all the old ones and using that as a clean slate going forward?

**Comment by ashthespy** [comment]
>Perhaps that is a good thing, and you could think yet another repo, archiving all the old ones and using that as a clean slate going forward?

I'd propose renaming the old build repo - it's got more stars ;-) 
Plus, given the lack of any dev there + new name, there aren't many risks of breaking history.
