### ISSUE TITLE
Customization of the screensaver (Photo/Cover Frame) "enhancement"

### ISSUE THREAD

**Issue by 60plus** [volumio/volumio3-os#57]
Hello 
I would like to propose extension of the screen saver function with the ability to display photos or album covers such as photo frame. When music doesn't play.
If there is already such a plugin or function I would be very grateful for indicating where I can set it up.

**Comment by ashthespy** [comment]
Wrong repo - [volumio/volumio3-backend](https://github.com/volumio/volumio3-backend) is a better bet..
