### ISSUE TITLE
node failure on x86 build

### ISSUE THREAD

**Issue by amjfrankenstein** [volumio/volumio3-os#67]
nodejs has no 32bit support after 9+ the script wants 14 i am unsure where or what to alter to change node version or if this will work at all

**Comment by ashthespy** [comment]
There will be other bits that fail on x86 -- https://github.com/volumio/Build/issues/478 
32 bits isn't officially supported..
But, look at what is being done for the Pi builds (to support armv6) and use https://unofficial-builds.nodejs.org/
