### ISSUE TITLE
NodeJS v14 EOL

### ISSUE THREAD

**Issue by ashthespy** [volumio/volumio3-os#70]
[14.xx is EOL as of 30-04-2023](https://github.com/nodejs/Release#end-of-life-releases).

While Node v16 would have been the smart bet, it will be EOL soon after ([Bringing forward the End-of-Life Date for Node.js v16](https://nodejs.org/en/blog/announcements/nodejs16-eol/))
<img src="https://raw.githubusercontent.com/nodejs/Release/main/schedule.svg" width="60%">

Would suggest jumping to Node v18. This would entail creating new `node_modules` bundles.

**Comment by timothyjward** [comment]
v18 or even v20 seems like the sensible choice.

**Comment by volumio** [comment]
I agree to go 18 or 20

But we need help with the plugin crypter. @ashthespy would you be able to help there?

**Comment by timothyjward** [comment]
We should also take this opportunity to update to the latest kew library version, and then start removing kew from the codebase. Native promises are part of Node now and will be a much better option for development (performance, interoperability, support of async/await...)

**Comment by ashthespy** [comment]
Native promises have been in nodejs for quite a while and async/await in Node v8.x, so you could start refactoring already..  

But I agree, modernizing the code base will go a long way towards more maintainable system.

**Comment by ashthespy** [comment]
FWIW, v16 is also EOL now, so v20 (supported until 2026) would be the logical choice to upgrade to at this point in time. 

<img src="https://github.com/volumio/volumio3-os/assets/16233271/4805c289-917d-444a-a528-bc7ecf699df3" width="80%">

**Comment by ashthespy** [comment]
Closing in favor of #172
