### ISSUE TITLE
armv8 (aarch64) installer bug

### ISSUE THREAD

**Issue by Alexandr2021i** [volumio/volumio3-os#93]
When selects any armv8 arch's, example:
`sudo ./build.sh -b armv8 -d rockpis -v 2.0`
we a got no directory exists: /build/amrv7/..., but installer creates /build/armv8/... before.

if FIX this in scripts, got another error:
`[ -- ] Installing /volumio/customPkgs/00libcurl4_7.74.0-1.2~bpo10+1_armv7.deb 
Selecting previously unselected package libcurl4:armhf.
(Reading database ... 26122 files and directories currently installed.)
Preparing to unpack .../00libcurl4_7.74.0-1.2~bpo10+1_armv7.deb ...
De-configuring libcurl4:arm64 (7.64.0-4+deb10u2) ...
Unpacking libcurl4:armhf (7.74.0-1.2~bpo10+1) ...
dpkg: error processing package libcurl4:armhf (--install):
 package libcurl4:armhf 7.74.0-1.2~bpo10+1 cannot be configured because libcurl4:arm64 is at a different version (7.64.0-4+deb10u2)
dpkg: error processing package libcurl4:arm64 (--install):
 package libcurl4:arm64 7.64.0-4+deb10u2 cannot be configured because libcurl4:armhf is at a different version (7.74.0-1.2~bpo10+1)
Processing triggers for libc-bin (2.28-10+deb10u1) ...
Errors were encountered while processing:
 libcurl4:armhf
 libcurl4:arm64
[ error ] Volumio chroot config failed [ chrootconfig.sh ]
[ error ] Error stack [main] <=  [ 76 /chrootconfig.sh ]
[ error ] Imagebuilder script failed!! 
[ error ] Error stack [source] <= [main] <=  [ 236 /home/alexandr/VOLUMIO/volumio3-os/scripts/makeimage.sh ]
[ -- ] Cleaning up image_tmp mounts 
[ -- ] Unmounting chroot temporary devices at /mnt/volumio/rootfs 
[ .. ] Cleaning loop device /dev/loop60 [ /dev/loop60: [66310]:8305234 (/home/alexandr/VOLUMIO/volumio3-os/Volumio-2.0-2023-10-02-rockpis.img) ]
[ .. ] Deleting image file 
`

**Comment by Darmur** [comment]
armv8 images are not supported anymore by the build script, please run the script with -b armv7

**Comment by ashthespy** [comment]
@Darmur I couldn't find any commit dropping support, when was this done? Perhaps then it's good to remove all the scripts to avoid confusion..
